= Risikoliste: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


In diesem Dokument sind die wesentlichen Risiken des Projekts aufgeführt.


== Attribute

Dabei werden folgende Attribute verwendet:

* *Typ*: Ressourcen, Geschäftlich, Technisch, Zeitlich
* *Auswirkung (IMP)*: Wert zwischen 1 (niedrig) und 5 (hoch), der die Auswirkungen auf das Projekt angibt, wenn das Risiko eintritt
* *Wahrscheinlichkeit (PRB)*: Prozentangabe für die Eintrittswahrscheinlichkeit des Risikos
* *Stärke (MAG)*: Produkt aus Auswirkung und Wahrscheinlichkeit (damit kann die Liste sortiert werden)

== Risiken

Die Risiken sind in folgender Tabelle: <<table_risks>> dargestellt. Das Datum des Dokuments oben gibt an, wann die Risikoliste zuletzt aktualisiert wurde.

// Die inkludierte csv-Datei "risks.csv" verwendet `;` Semmikolons als Trennzeichen. Achten Sie beim Export als csv-Datei auf das Angeben des entsprechenden Trennzeichens. Verwenden Sie stattdessen `,` Kommas, kann das Tabellenattribut `separator=` weggelassen werden oder muss entprechend angepasst werden.

// PDF-Export: Seite im Querformat
[.landscape]
<<<

// table risks
[#table_risks]
.Risiken
[%header, format="csv", separator=";", cols="^1,^2,3,4,3,^1,^1,^1,3,4"]
|===
include::risks.csv[]
|===

// PDF-Export: Seite zurück zum Hochformat
[.portrait]
<<<
